defmodule OpenMuWebWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :open_mu_web

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_open_mu_web_key",
    signing_salt: "5HvB7spv",
    # Encrypted (not only signed) cookie: the session will carry the account id.
    encryption_salt: "A5XIadoq",
    same_site: "Lax",
    # 30 days, like the NextAuth session of the Next.js app.
    max_age: 30 * 24 * 60 * 60
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :open_mu_web,
    gzip: not code_reloading?,
    only: OpenMuWebWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    # Phoenix.Ecto.CheckRepoStatus is intentionally not used: the database schema is
    # owned by OpenMU, so Ecto must not prompt for (or run) migrations on page load.
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  # Plug.Parsers that tolerates malformed JSON on /api/* (see the module doc).
  plug OpenMuWebWeb.Plugs.LenientParsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug OpenMuWebWeb.Router
end
