defmodule OpenMuWeb.News.Article do
  @moduledoc """
  `data."OpenMuWeb_News"` — the only website-owned table. `id` and
  `creationDate` are generated by the database defaults. `author` holds the
  name of the Game Master character who created the news.
  """
  use Ecto.Schema

  @schema_prefix "data"
  @primary_key {:id, :binary_id, autogenerate: false, read_after_writes: true}

  schema "OpenMuWeb_News" do
    field :title, :string
    field :body, :string
    field :author, :string
    field :creation_date, :naive_datetime_usec, source: :creationDate, read_after_writes: true
  end
end
